# Build sdme from source with vendored crate dependencies.
#
# sdme is a leaf application, so its transitive crate dependencies are bundled
# into the SRPM as a vendor tarball (Source1) rather than packaged as separate
# rust-* crates. The Fedora Rust Packaging Guidelines allow this for
# applications (not libraries).
#
# The vendor tarball is generated by the maintainer, not fetched automatically.
# See packaging/fedora/build-in-container.sh and packaging/fedora/README.md.

%global crate sdme

Name:           sdme
Version:        0.16.0
Release:        1%{?dist}
Summary:        The systemd machine editor

# sdme itself is MIT. Bundled crates carry their own (MIT/Apache-2.0-family)
# licenses; the full breakdown is generated at build time into
# LICENSE.dependencies and cargo-vendor.txt and shipped as %%license files.
# For the official Fedora submission, replace the tag below with the combined
# SPDX expression that %%cargo_license computes over the vendored tree.
License:        MIT
URL:            https://github.com/fiorix/sdme
# Canonical upstream source is the crates.io release tarball (no git tag needed).
Source0:        %{crates_source}
Source1:        %{crate}-%{version}-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 25

# systemd-nspawn and machinectl are provided by systemd-container.
# The >= 255 floor matches every other channel (Debian control, both PKGBUILDs,
# and the binary's own "Runs on Linux with systemd >= 255"), so dnf decides at
# install time instead of sdme failing at runtime. It earns its keep on el9:
# Stream 9's base systemd is 252, but the CentOS Hyperscale SIG rebases it to
# 260.x (.hs.el9), so one el9 RPM installs on a Hyperscale-enabled host and is
# refused on a base Stream 9. Fedora and Stream 10 (257) clear it comfortably.
Requires:       systemd >= 255
Requires:       systemd-container
# qemu-nbd (from qemu-img) is only needed for QCOW2 image import; sdme checks
# for it at runtime with a clear error. Suggests (not Recommends) so dnf does
# not install it and its dependency chain by default; matches the Debian
# package's Suggests: qemu-utils.
Suggests:       qemu-img

%description
sdme boots systemd-nspawn containers using overlayfs copy-on-write layers,
with OCI registry integration and Kubernetes Pod YAML support. Default
containers are overlayfs clones of the host root filesystem; rootfs images
from other distributions can be imported and booted instead. Runs on Linux
with systemd and requires root.

%prep
%autosetup -n %{crate}-%{version} -p1
# Unpack the vendored crate sources, then point cargo at them (offline build).
tar -xf %{SOURCE1}
%cargo_prep -v vendor

%build
%cargo_vendor_manifest
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies
# build.rs compiles and embeds the sdme-kube-probe binary. It spawns a nested
# cargo build that inherits the vendored, offline cargo config from
# %%cargo_prep, so no network access is required.
# Mark this as a Copr/dnf-managed build so `sdme upgrade` defers to the package
# manager instead of overwriting the rpm-owned binary.
export SDME_CHANNEL=copr
%cargo_build

%install
%cargo_install
# sdme has a [lib], so %%cargo_install also stages the crate registry sources
# for a -devel subpackage. This is an application-only package: drop them so the
# unpackaged-files check passes and only the binary and completions ship.
rm -rf %{buildroot}%{_datadir}/cargo/registry
# Shell completions are emitted by the freshly built binary (no root needed).
install -d %{buildroot}%{_datadir}/bash-completion/completions
install -d %{buildroot}%{_datadir}/zsh/site-functions
install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/%{crate} config completions bash > %{buildroot}%{_datadir}/bash-completion/completions/%{crate}
%{buildroot}%{_bindir}/%{crate} config completions zsh  > %{buildroot}%{_datadir}/zsh/site-functions/_%{crate}
%{buildroot}%{_bindir}/%{crate} config completions fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/%{crate}.fish

%check
# Run the unit tests during the build (unprivileged, offline against vendor).
# build.rs skips the probe under CARGO_CFG_TEST, so no network or probe needed.
%cargo_test

%files
%license LICENSE
%license cargo-vendor.txt
%license LICENSE.dependencies
%doc README.md
%{_bindir}/%{crate}
%{_datadir}/bash-completion/completions/%{crate}
%{_datadir}/zsh/site-functions/_%{crate}
%{_datadir}/fish/vendor_completions.d/%{crate}.fish

%changelog
* Sat Jul 18 2026 Alexandre Fiori <fiorix@gmail.com> - 0.16.0-1
- Add btrfs storage backend support to Kubernetes pods: `sdme kube apply/create`
  now accept `--storage btrfs` and `--disk`, building the combined pod rootfs as
  a copy-on-write subvolume snapshot of `--base-fs`.
- Add nested user namespace support: `--userns-nested N` and the
  `userns_nested_ranges` config reserve extra 64K UID/GID ranges so containers
  can host further namespaced workloads inside an existing user namespace.

* Fri Jul 17 2026 Alexandre Fiori <fiorix@gmail.com> - 0.15.0-1
- Require systemd >= 255 explicitly, which is the version sdme has always
  needed, so dnf declines the install where it cannot run instead of letting
  it fail at runtime. Fedora and CentOS Stream 10 are unaffected. On Stream 9
  (systemd 252), enable the CentOS Hyperscale SIG, which rebases systemd to
  260.x; dnf then pulls it in automatically.
- Packaging release: no functional changes to sdme itself.

* Fri Jul 17 2026 Alexandre Fiori <fiorix@gmail.com> - 0.14.0-1
- Accept bare syscall names in --system-call-filter, alongside the @group
  syntax systemd-nspawn already took, and make btrfs subvolume removal
  recursive so nested subvolumes no longer block `sdme rm`.

* Wed Jul 15 2026 Alexandre Fiori <fiorix@gmail.com> - 0.13.1-1
- Make the btrfs storage default usable: expose default_storage_backend and
  btrfs_pool_size in `sdme config get` and `sdme config set`, and fall back to
  overlay for host-rootfs containers when btrfs is the configured default (an
  explicit --storage btrfs on a host rootfs is still rejected).

* Wed Jul 15 2026 Alexandre Fiori <fiorix@gmail.com> - 0.13.0-1
- Add a btrfs storage backend (--storage btrfs) for imported and OCI rootfs:
  copy-on-write subvolume snapshots enabling nested containers, native
  user-namespace idmapping that preserves suid and xattrs, and per-container
  disk quotas (--disk). Overlay remains the default backend. --disk is
  refused when the datadir filesystem's btrfs quotas are managed externally,
  since enforcement cannot be guaranteed there.

* Mon Jul 14 2026 Alexandre Fiori <fiorix@gmail.com> - 0.12.1-1
- Fix --userns pre-chown stripping setuid/setgid bits (e.g. sudo) when the
  kernel lacks idmapped-mount support on overlayfs. The recursive UID/GID
  shift ran lchown without re-applying the mode, so chown's kernel-side
  clearing of S_ISUID/S_ISGID left setuid binaries broken after boot. The
  mode is now restored after the shift.

* Sun Jul 12 2026 Alexandre Fiori <fiorix@gmail.com> - 0.12.0-1
- Update to 0.12.0.
- Register nspawn containers with systemd-nspawn --keep-unit (plus
  Slice=machine.slice and DelegateSubgroup= on systemd 256+) to avoid the
  boot-time machined scope-creation stall.
- Add an opt-in per-container restart policy (--restart no|on-failure) and make
  sdme stop --kill and sdme rm restart-safe.

* Fri Jul 10 2026 Alexandre Fiori <fiorix@gmail.com> - 0.11.1-1
- Update to 0.11.1.
- Disable self-upgrade on this Copr build: `sdme upgrade` now defers to dnf
  instead of overwriting the rpm-managed binary, and the background update
  check is suppressed.

* Fri Jul 10 2026 Alexandre Fiori <fiorix@gmail.com> - 0.11.0-1
- Update to 0.11.0.

* Thu Jul 09 2026 Alexandre Fiori <fiorix@gmail.com> - 0.10.3-2
- Demote qemu-img from Recommends to Suggests; only needed for QCOW2
  image import, not core container operations.

* Thu Jul 09 2026 Alexandre Fiori <fiorix@gmail.com> - 0.10.3-1
- Update to 0.10.3.

* Wed Jul 08 2026 Alexandre Fiori <fiorix@gmail.com> - 0.10.1-1
- Initial Fedora package.
