# Build sdme from source with vendored crate dependencies.
#
# sdme is a leaf application, so its transitive crate dependencies are bundled
# into the SRPM as a vendor tarball (Source1) rather than packaged as separate
# rust-* crates. The Fedora Rust Packaging Guidelines allow this for
# applications (not libraries).
#
# The vendor tarball is generated by the maintainer, not fetched automatically.
# See packaging/fedora/build-in-container.sh and packaging/fedora/README.md.

%global crate sdme

Name:           sdme
Version:        0.10.3
Release:        1%{?dist}
Summary:        The systemd machine editor

# sdme itself is MIT. Bundled crates carry their own (MIT/Apache-2.0-family)
# licenses; the full breakdown is generated at build time into
# LICENSE.dependencies and cargo-vendor.txt and shipped as %%license files.
# For the official Fedora submission, replace the tag below with the combined
# SPDX expression that %%cargo_license computes over the vendored tree.
License:        MIT
URL:            https://github.com/fiorix/sdme
# Canonical upstream source is the crates.io release tarball (no git tag needed).
Source0:        %{crates_source}
Source1:        %{crate}-%{version}-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 25

# systemd-nspawn and machinectl are provided by systemd-container.
Requires:       systemd
Requires:       systemd-container
# qemu-img is used for raw/qcow image workflows, not for core container ops.
Recommends:     qemu-img

%description
sdme boots systemd-nspawn containers using overlayfs copy-on-write layers,
with OCI registry integration and Kubernetes Pod YAML support. Default
containers are overlayfs clones of the host root filesystem; rootfs images
from other distributions can be imported and booted instead. Runs on Linux
with systemd and requires root.

%prep
%autosetup -n %{crate}-%{version} -p1
# Unpack the vendored crate sources, then point cargo at them (offline build).
tar -xf %{SOURCE1}
%cargo_prep -v vendor

%build
%cargo_vendor_manifest
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies
# build.rs compiles and embeds the sdme-kube-probe binary. It spawns a nested
# cargo build that inherits the vendored, offline cargo config from
# %%cargo_prep, so no network access is required.
%cargo_build

%install
%cargo_install
# sdme has a [lib], so %%cargo_install also stages the crate registry sources
# for a -devel subpackage. This is an application-only package: drop them so the
# unpackaged-files check passes and only the binary and completions ship.
rm -rf %{buildroot}%{_datadir}/cargo/registry
# Shell completions are emitted by the freshly built binary (no root needed).
install -d %{buildroot}%{_datadir}/bash-completion/completions
install -d %{buildroot}%{_datadir}/zsh/site-functions
install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/%{crate} config completions bash > %{buildroot}%{_datadir}/bash-completion/completions/%{crate}
%{buildroot}%{_bindir}/%{crate} config completions zsh  > %{buildroot}%{_datadir}/zsh/site-functions/_%{crate}
%{buildroot}%{_bindir}/%{crate} config completions fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/%{crate}.fish

%check
# Run the unit tests during the build (unprivileged, offline against vendor).
# build.rs skips the probe under CARGO_CFG_TEST, so no network or probe needed.
%cargo_test

%files
%license LICENSE
%license cargo-vendor.txt
%license LICENSE.dependencies
%doc README.md
%{_bindir}/%{crate}
%{_datadir}/bash-completion/completions/%{crate}
%{_datadir}/zsh/site-functions/_%{crate}
%{_datadir}/fish/vendor_completions.d/%{crate}.fish

%changelog
* Wed Jul 08 2026 Alexandre Fiori <fiorix@gmail.com> - 0.10.1-1
- Initial Fedora package.
